In [ ]:
import numpy as np
from scipy.linalg import solve

def gaussian_elimination_partial_pivot(A, b, tol=1e-12, verbose=False):
    """
    Eliminação gaussiana com pivotamento parcial.
    Retorna o vetor solução x.
    Se verbose=True imprime os passos intermediários.
    """
    A = A.astype(float).copy()
    b = b.astype(float).copy()
    n = len(b)

    for k in range(n-1):
        # Escolhe linha do maior pivô absoluto
        max_row = np.argmax(np.abs(A[k:, k])) + k
        if abs(A[max_row, k]) < tol:
            raise ValueError("Matriz singular ou quase singular.")

        # Troca de linhas se necessário
        if max_row != k:
            A[[k, max_row]] = A[[max_row, k]]
            b[[k, max_row]] = b[[max_row, k]]
            if verbose:
                print(f"\nTroca de linhas {k} <-> {max_row}")
                print("A:\n", A)
                print("b:", b)

        # Eliminação
        pivot = A[k, k]
        for i in range(k+1, n):
            m = A[i, k] / pivot
            A[i, k:] -= m * A[k, k:]
            b[i] -= m * b[k]
            if verbose:
                print(f"\nEliminando linha {i}, m={m}")
                print("A:\n", A)
                print("b:", b)

    # Substituição retroativa
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        if abs(A[i, i]) < tol:
            raise ValueError("Zero na diagonal durante substituição retroativa.")
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    if verbose:
        print("\nMatriz escalonada (U):\n", A)
        print("Vetor b modificado:", b)
        print("Solução encontrada:", x)

    return x


# ========================
# Teste no sistema (a)
# ========================

A = np.array([[1, 1, 1],
              [4, 4, 2],
              [2, 1,-1]], dtype=float)

b = np.array([1, 2, 0], dtype=float)

# Solução com nosso método
x_gauss = gaussian_elimination_partial_pivot(A, b, verbose=True)

# Solução com scipy
x_scipy = solve(A, b)

print("\n==============================")
print("Solução pelo nosso método:", x_gauss)
print("Solução pelo scipy.linalg.solve:", x_scipy)
print("==============================")



Troca de linhas 0 <-> 1
A:
 [[ 4.  4.  2.]
 [ 1.  1.  1.]
 [ 2.  1. -1.]]
b: [2. 1. 0.]

Eliminando linha 1, m=0.25
A:
 [[ 4.   4.   2. ]
 [ 0.   0.   0.5]
 [ 2.   1.  -1. ]]
b: [2.  0.5 0. ]

Eliminando linha 2, m=0.5
A:
 [[ 4.   4.   2. ]
 [ 0.   0.   0.5]
 [ 0.  -1.  -2. ]]
b: [ 2.   0.5 -1. ]

Troca de linhas 1 <-> 2
A:
 [[ 4.   4.   2. ]
 [ 0.  -1.  -2. ]
 [ 0.   0.   0.5]]
b: [ 2.  -1.   0.5]

Eliminando linha 2, m=-0.0
A:
 [[ 4.   4.   2. ]
 [ 0.  -1.  -2. ]
 [ 0.   0.   0.5]]
b: [ 2.  -1.   0.5]

Matriz escalonada (U):
 [[ 4.   4.   2. ]
 [ 0.  -1.  -2. ]
 [ 0.   0.   0.5]]
Vetor b modificado: [ 2.  -1.   0.5]
Solução encontrada: [ 1. -1.  1.]

Solução pelo nosso método: [ 1. -1.  1.]
Solução pelo scipy.linalg.solve: [ 1. -1.  1.]


In [ ]:
import numpy as np
from scipy.linalg import solve

def gaussian_elimination_partial_pivot(A, b, tol=1e-12, verbose=False):
    """
    Eliminação gaussiana com pivotamento parcial.
    Retorna o vetor solução x.
    Se verbose=True imprime os passos intermediários.
    """
    A = A.astype(float).copy()
    b = b.astype(float).copy()
    n = len(b)

    for k in range(n-1):
        # Escolhe linha do maior pivô absoluto
        max_row = np.argmax(np.abs(A[k:, k])) + k
        if abs(A[max_row, k]) < tol:
            raise ValueError("Matriz singular ou quase singular.")

        # Troca de linhas se necessário
        if max_row != k:
            A[[k, max_row]] = A[[max_row, k]]
            b[[k, max_row]] = b[[max_row, k]]
            if verbose:
                print(f"\nTroca de linhas {k} <-> {max_row}")
                print("A:\n", A)
                print("b:", b)

        # Eliminação
        pivot = A[k, k]
        for i in range(k+1, n):
            m = A[i, k] / pivot
            A[i, k:] -= m * A[k, k:]
            b[i] -= m * b[k]
            if verbose:
                print(f"\nEliminando linha {i}, m={m}")
                print("A:\n", A)
                print("b:", b)

    # Substituição retroativa
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        if abs(A[i, i]) < tol:
            raise ValueError("Zero na diagonal durante substituição retroativa.")
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    if verbose:
        print("\nMatriz escalonada (U):\n", A)
        print("Vetor b modificado:", b)
        print("Solução encontrada:", x)

    return x


# ========================
# Teste no sistema (b)
# ========================

A = np.array([[7, -7, 1],
              [-3, 3, 2],
              [7, 7, -72]], dtype=float)

b = np.array([1, 2, 7], dtype=float)

# Solução com nosso método
x_gauss = gaussian_elimination_partial_pivot(A, b, verbose=True)

# Solução com scipy
x_scipy = solve(A, b)

print("\n==============================")
print("Solução pelo nosso método:", x_gauss)
print("Solução pelo scipy.linalg.solve:", x_scipy)
print("==============================")



Eliminando linha 1, m=-0.42857142857142855
A:
 [[  7.          -7.           1.        ]
 [  0.           0.           2.42857143]
 [  7.           7.         -72.        ]]
b: [1.         2.42857143 7.        ]

Eliminando linha 2, m=1.0
A:
 [[  7.          -7.           1.        ]
 [  0.           0.           2.42857143]
 [  0.          14.         -73.        ]]
b: [1.         2.42857143 6.        ]

Troca de linhas 1 <-> 2
A:
 [[  7.          -7.           1.        ]
 [  0.          14.         -73.        ]
 [  0.           0.           2.42857143]]
b: [1.         6.         2.42857143]

Eliminando linha 2, m=0.0
A:
 [[  7.          -7.           1.        ]
 [  0.          14.         -73.        ]
 [  0.           0.           2.42857143]]
b: [1.         6.         2.42857143]

Matriz escalonada (U):
 [[  7.          -7.           1.        ]
 [  0.          14.         -73.        ]
 [  0.           0.           2.42857143]]
Vetor b modificado: [1.         6.         2.4285

In [ ]:
import numpy as np
from scipy.linalg import solve

def gaussian_elimination_partial_pivot(A, b, tol=1e-12, verbose=False):
    """
    Eliminação gaussiana com pivotamento parcial.
    Retorna o vetor solução x.
    Se verbose=True imprime os passos intermediários.
    """
    A = A.astype(float).copy()
    b = b.astype(float).copy()
    n = len(b)

    for k in range(n-1):
        # Escolhe linha do maior pivô absoluto
        max_row = np.argmax(np.abs(A[k:, k])) + k
        if abs(A[max_row, k]) < tol:
            raise ValueError("Matriz singular ou quase singular.")

        # Troca de linhas se necessário
        if max_row != k:
            A[[k, max_row]] = A[[max_row, k]]
            b[[k, max_row]] = b[[max_row, k]]
            if verbose:
                print(f"\nTroca de linhas {k} <-> {max_row}")
                print("A:\n", A)
                print("b:", b)

        # Eliminação
        pivot = A[k, k]
        for i in range(k+1, n):
            m = A[i, k] / pivot
            A[i, k:] -= m * A[k, k:]
            b[i] -= m * b[k]
            if verbose:
                print(f"\nEliminando linha {i}, m={m}")
                print("A:\n", A)
                print("b:", b)

    # Substituição retroativa
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        if abs(A[i, i]) < tol:
            raise ValueError("Zero na diagonal durante substituição retroativa.")
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    if verbose:
        print("\nMatriz escalonada (U):\n", A)
        print("Vetor b modificado:", b)
        print("Solução encontrada:", x)

    return x


# ========================
# Teste no sistema (c)
# ========================

A = np.array([[1, 2, 3, 4],
              [2, 2, 3, 4],
              [3, 3, 3, 4],
              [4, 4, 4, 4]], dtype=float)

b = np.array([20, 22, 22, 24], dtype=float)

# Solução com nosso método
x_gauss = gaussian_elimination_partial_pivot(A, b, verbose=True)

# Solução com scipy
x_scipy = solve(A, b)

print("\n==============================")
print("Solução pelo nosso método:", x_gauss)
print("Solução pelo scipy.linalg.solve:", x_scipy)
print("==============================")



Troca de linhas 0 <-> 3
A:
 [[4. 4. 4. 4.]
 [2. 2. 3. 4.]
 [3. 3. 3. 4.]
 [1. 2. 3. 4.]]
b: [24. 22. 22. 20.]

Eliminando linha 1, m=0.5
A:
 [[4. 4. 4. 4.]
 [0. 0. 1. 2.]
 [3. 3. 3. 4.]
 [1. 2. 3. 4.]]
b: [24. 10. 22. 20.]

Eliminando linha 2, m=0.75
A:
 [[4. 4. 4. 4.]
 [0. 0. 1. 2.]
 [0. 0. 0. 1.]
 [1. 2. 3. 4.]]
b: [24. 10.  4. 20.]

Eliminando linha 3, m=0.25
A:
 [[4. 4. 4. 4.]
 [0. 0. 1. 2.]
 [0. 0. 0. 1.]
 [0. 1. 2. 3.]]
b: [24. 10.  4. 14.]

Troca de linhas 1 <-> 3
A:
 [[4. 4. 4. 4.]
 [0. 1. 2. 3.]
 [0. 0. 0. 1.]
 [0. 0. 1. 2.]]
b: [24. 14.  4. 10.]

Eliminando linha 2, m=0.0
A:
 [[4. 4. 4. 4.]
 [0. 1. 2. 3.]
 [0. 0. 0. 1.]
 [0. 0. 1. 2.]]
b: [24. 14.  4. 10.]

Eliminando linha 3, m=0.0
A:
 [[4. 4. 4. 4.]
 [0. 1. 2. 3.]
 [0. 0. 0. 1.]
 [0. 0. 1. 2.]]
b: [24. 14.  4. 10.]

Troca de linhas 2 <-> 3
A:
 [[4. 4. 4. 4.]
 [0. 1. 2. 3.]
 [0. 0. 1. 2.]
 [0. 0. 0. 1.]]
b: [24. 14. 10.  4.]

Eliminando linha 3, m=0.0
A:
 [[4. 4. 4. 4.]
 [0. 1. 2. 3.]
 [0. 0. 1. 2.]
 [0. 0. 0. 1.]]
b: [24. 